# Среда R

**R** - это язык программирования для статистических вычислений и графического представления информации, бесплатное программное обеспечение с открытым исходным кодом, доступное для Windows, macOS и Linux. R широко используется статистиками, специалистами по обработке данных и инженерами машинного обучения, поддерживает практически все виды статистического анализа. RStudio работает как IDE поверх R, позволяя визуализировать вычисления.

Пользователи Windows и macOS могут скачать R на сайте CRAN (Comprehensive R Archive Network). Пользователи Linux и Unix могут установить пакеты R с помощью своего инструмента управления пакетами.

## Windows

1.  Перейдите на страницу <http://www.r-project.org/> в своем браузере.

2.  Нажмите CRAN. Вы увидите список зеркал сайта, упорядоченных по странам.

3.  Выберите ближайший к вам сайт или самый первый указанный в верхней части списка (0-Cloud), который, как правило, хорошо работает для большинства местоположений (<https://cloud.r-project.org/>).

4.  Нажмите Download R for Windows (Скачать R для Windows) в разделе Download and Install R (Скачать и установить R).

5.  Нажмите base.

6.  Нажмите на ссылку, чтобы скачать последнюю версию R (файл.exe).

7.  По завершении загрузки дважды щелкните файл .exe и ответьте на привычные вопросы.

## macOS

1.  Перейдите на страницу <http://www.r-project.org/> в своем браузере.

2.  Нажмите CRAN. Вы увидите список зеркал сайта, упорядоченных по странам.

3.  Выберите ближайший к вам сайт или самый первый указанный в верхней части списка (0-Cloud), который, как правило, хорошо работает для большинства местоположений.

4.  Нажмите Download R for (Mac) OS X (Скачать R для (Mac) OS X).

5.  Нажмите на файл .pkg для последней версии R в разделе Latest release (Последний выпуск), чтобы скачать его.

6.  По завершении загрузки дважды щелкните файл .pkg и ответьте на привычные вопросы.

Для установки RStudio необходимо загрузить последнюю версию установщика для вашей платформы с сайта RStudio: (<https://rstudio.com/products/rstudio/download/>). Версию RStudio Desktop с открытым исходным кодом можно скачать и использовать бесплатно.

**Примечание:**

Просмотр документации: `help.start()`

Быстрый вызов функции: `?mean`

Поиск текстового шаблона функции: `??mean`
