---
title: "ВВЕДЕНИЕ В ЯЗЫК R: пакеты {dplyr}, {ggplot2}, {stats}"
author: "М.Л. Никонорова, А.В. Тишков, Н.П. Волков."
site: bookdown::bookdown_site
output: pdf_document
editor_options:
  markdown:
    wrap: sentence
---

# Об издании

УДК

ББК

            М

            А в т о р ы :

            Р е ц е н з е н т :

*Утверждено на заседании ЦМК по медико--биологическим*

*и медико--профилактическим дисциплинам*

*ФГБОУ ВО ПСПбГМУ им. И.П. Павлова.*

*Протокол № ..... от ................. 2024 г.*

            Введение ы язык R: пакеты {dplyr}, {ggplot2}, {stats} :
            учебное пособие / М.Л. Никонорова, А.В. Тишков, Н.П.Волков.
-- СПб.: РИЦ ПСПбГМУ, 2024.
....
с.

            ISBN

            В данном учебном пособие рассмотрены типы, структуры и ввод данных в языке программирования R, управление данными. Приведены практические примеры описательной статистики с визуализацией биомедицинских данных. Рассмотрены пакеты {dplyr}, {ggplot2} и {stat}. 
            Учебное пособие предназначено для студентов лечебного, стоматологического, педиатрического факультетов и факультета клинической психологии, для студентов цифровой кафедры. Пособие может быть полезно клиническим ординаторам и аспирантам при статистической обработке большого объема информации, представления обобщенных клинических данных и их статистического анализа.

ISBN

© М.Л. Никонорова, А.В. Тишков, Н.П. Волков

© РИЦ ПСПбГМУ, 2024
